./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=0 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=50 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=100 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=150 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=200 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=250 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=300 --RSQcut=0 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=0 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=50 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=100 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=150 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=200 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=250 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=300 --RSQcut=0.025 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=0 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=50 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=100 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=150 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=200 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=250 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC
./MakeFitAIC --inputFile=DoublePhoton_22Jan2013_Run2012ABCD_v9.root --treeName=SusyHggTree --MRcut=300 --RSQcut=0.05 --dataMode=data --category=highres --fitMode=AIC

